language: python
cache: pip
dist: xenial
python:
- '2.7'
- '3.6'
- '3.7'
env:
- SALT=2019.2.0
- SALT=2018.3.4
- SALT=2017.7.8
- SALT=2016.11.10
install:
- pip install pytest salt~=$SALT
script:
- python setup.py install
- pytest -v
matrix:
  exclude:
  - python: '3.6'
    env: SALT=2016.11.10
  - python: '3.7'
    env: SALT=2017.7.8
  - python: '3.7'
    env: SALT=2016.11.10
