# -*- vim: ft=yaml:sw=2 -*-
name: Python Package

on: [push]

jobs:
  Test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        python: ["3.9", "3.8", "3.7", "3.6"]
        salt: ["3002.0"]
        include:
          - { salt: "2017.7.4", python: "3.6" }
          - { salt: "2018.3.4", python: "3.6" }
          - { salt: "2018.3.4", python: "3.7" }
          - { salt: "2019.2.0", python: "3.6" }
          - { salt: "2019.2.0", python: "3.7" }
          - { salt: "3000.0", python: "3.6" }
          - { salt: "3000.0", python: "3.7" }
          - { salt: "3001.0", python: "3.6" }
          - { salt: "3001.0", python: "3.7" }
          - { salt: "3001.0", python: "3.8" }

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest salt~=${{ matrix.salt }}
      - name: Build package
        run: python setup.py install
      - name: Test
        run: pytest -v
